- name: Analyze User Activity
  id: analyze_user_activity
  uses: peter-murray/inactive-users-action@v1
  with:
    token: ${{ secrets.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}}
    organization: Fiserv
    activity_days: 90

- name: Save User Activity Report
  uses: actions/upload-artifact@v2
  with:
    name: reports
    path: |
      ${{ steps.analyze_user_activity.outputs.github/report-cvs.txt}}
