blank_issues_enabled: false
contact_links:
  - name: Developer Studio Support
    url: https://developer.fiserv.com/support
    about: View our official Developer Studio FAQ and release notes.
  - name: Developer Studio Tenant Support
    url: https://developer.fiserv.com/product/TenantSupport
    about: View our Developer Studio documentation for various product configurations and support. This requires an account on Developer Studio.
