---
name: Onboard a new tenant
description: New tenant onboarding
title: Onboard a new tenant
labels:
  - Onboard New Tenant
assignees:
  - russnicoletti
  - minh-pham1
body:
  - type: markdown
    attributes:
      value: |
        
        ---
        
        Thank you for taking the time to submit the Tenant Onboarding form. To seemlessly onboard you, we need some information. Kindly review our onboarding documents before submitting this form - https://fiserv.gitbook.io/tenant-docs/ for common questions.
  - type: input
    id: Name-Of-Product
    attributes:
      label: Name of your product / tenant
      description: Provide the name of the product as would appear on Developer Studio
      placeholder: TENANT-NAME
    validations:
      required: true
  - type: input
    id: Description-Of-Product
    attributes:
      label: Short Description of Tenant
      description: Provide a short description of the product. Limit 112 characters.
      placeholder: This is a short description with less than 112 characters of the product.
    validations:
      required: true
  - type: dropdown
    id: Tenant-Type
    validations:
      required: true
    attributes:
      label: Type of Tenant
      description: |
        Specify the type of integration required.

        - Full service: Developer Studio product with both documentation and API specs
        - Doc only: Developer Studio product with only markdown documentation
        - Link out: Listed under Developer Studio catalog with link redirecting to tenant provided website
      options:
        - "Full service"
        - "Doc only"
        - "Link out"
  - type: input
    id: Team-Members
    attributes:
      label: Team Members
      description: Provide the GitHub usernames registered with Fiserv email address.
      placeholder: tonyStark01, wanda01
    validations:
      required: true
  - type: input
    id: Bug-Reporting
    attributes:
      label: Bug Reporting
      description: Provide the GitHub usernames registered with Fiserv email address.
      placeholder: tonyStark01, wanda01
    validations:
      required: true
  - type: input
    id: Feedback-Reporting
    attributes:
      label: Feedback Reporting
      description: Provide the GitHub usernames registered with Fiserv email address.
      placeholder: thor01, tonyStark01
    validations:
      required: true
  - type: input
    id: Enhancement-Reporting
    attributes:
      label: Enhancement Reporting
      description: Provide the GitHub usernames registered with Fiserv email address.
      placeholder: tonyStark01, loki01
    validations:
      required: true
  - type: input
    id: External-Link
    attributes:
      label: External link
      description: Provide external url to your product/developer portal if you have chosen 'Link out' as the 'Type of Tenant'
      placeholder: https://www.fiserv.com
  - type: dropdown
    id: Internal-Tenant
    attributes:
        label: Internal tenant
        description: Is this product only for Fiserv's internal use (valid user with work email login required on DevStudio portal to view)? If not sure, please select 'No'
        options:
         - "No"
         - "Yes"
    validations:
      required: true
  - type: dropdown
    id: Carat
    attributes:
        label: Product of Carat
        description: Is this product for Fiserv's Carat Solutions? If not sure, please select 'No'
        options:
         - "No"
         - "Yes"
    validations:
      required: true
  - type: dropdown
    id: Product-Areas-Payments
    attributes:
        label: Payments solution area
        description: Does you product fall under Payments category?
        options:
         - "Yes"
         - "No"
    validations:
      required: true
  - type: dropdown
    id: customer-segments-for-payments
    attributes:
      label: Customer Segments for Payments
      description: Specify the type(s) of applicable segment(s). Required if you selected Payments above.
      options:
      - SMB
      - Enterprise
      multiple: true
  - type: dropdown
    id: capabilities-for-payments
    attributes:
      label: Capabilities for Payments
      description: Specify the type(s) of capabilities your services provide. Required if you selected Payments above.
      options:
        - Analytics
        - Boarding & Management
        - Disbursements
        - Omni-Channel
        - Value Added Services
      multiple: true
  - type: dropdown
    id: Product-Areas-Banking
    attributes:
        label: Banking solution area
        description: Does your product fall under Banking category?
        options:
          - "Yes"
          - "No"
    validations:
      required: true
  - type: dropdown
    id: customer-segments-for-banking
    attributes:
      label: Customer Segments for Banking
      description: Specify the type(s) of applicable segment(s). Required if you selected Banking above.
      options:
        - Bank
        - Credit Union
        - Large Financial Institution
      multiple: true
  - type: dropdown
    id: capabilities-for-banking
    attributes:
      label: Capabilities for Banking
      description: Specify the type(s) of capabalities your services provide. Required if you selected Banking above.
      options:
        - Banking as a Service
        - Financial Data Management
        - Issuing
        - Licensing
      multiple: true
  - type: dropdown
    id: region-of-operation
    attributes:
      label: Region of Operation
      description: Select your product's operational region. 
      options:
        - North America
        - EMEA
        - LATAM
        - APAC
      multiple: true
      
  - type: markdown
    attributes:
      value: <h4> API Mock Sandbox </h4>
        <I> Details regarding API sandbox if your product is Full Service with API specs and would like for user to have a playground to test mock calls/payloads.
        You may request to change sandbox type at a later date with a separate Github Issue request.
        If you are a doc-only tenant, please select `None`</I>
      
  - type: dropdown
    id: mock
    attributes:
      label: Mock Sandbox
      description: |
        Are you planning on writing API spec files to be mocked using Developer Studio's internal mock server (returning mock data based on the request)?
      options:
        - "Developer Studio Prism Server"
        - "Tenant Provided Sandbox Environment"
        - "N/A"
    validations:
      required: true

  - type: dropdown
    id: contact-sales
    attributes:
      label: Sales Contact
      description: Do you want to provide a contact for sales purposes?
      options:
        - "Yes"
        - "No"
      default: 1
    validations:
      required: true
  - type: textarea
    id: contact-sales-person
    attributes:
      label: Sales Contact Information
      description: If yes, please provide the name and email of your sales contact.
      placeholder: "Leeroy Jenkins (leeroy.jenkins@fiserv.com)"
