---
name: Onboard Tenant
description: New tenant onboarding
title: Tenant Onboarding
labels:
  - Onboard New Tenant
assignees: sfiserv
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behaviour in the existing issues. 
        
        ---
        
        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.
  - type: input
    id: Name-Of-Product
    attributes:
      label: Name of your product / tenant
      description: Provide the name of the product as would appear on Developer Studio
      placeholder: ABC Product
    validations:
      required: true
  - type: checkboxes
    id: Tenant-Type
    validations:
      required: true
    attributes:
      label: Type of Tenant
      description: Specify the type of integration required.
      options:
      - label: Full service
      - label: Doc only
      - label: Link out
  - type: input
    id: Team-Members
    attributes:
      label: Team Members
      description: Provide the GitHub usernames registered with Fiserv email address.
      placeholder: tonyStark01
    validations:
      required: true
  - type: input
    id: Bug-Reporting
    attributes:
      label: Bug Reporting
      description: Provide the GitHub usernames registered with Fiserv email address.
      placeholder: tonyStark01, wanda01
    validations:
      required: true
  - type: input
    id: Feedback-Reporting
    attributes:
      label: Feedback Reporting
      description: Provide the GitHub usernames registered with Fiserv email address.
      placeholder: thor01, tonyStark01
    validations:
      required: true
  - type: input
    id: Enhancement-Reporting
    attributes:
      label: Enhancement Reporting
      description: Provide the GitHub usernames registered with Fiserv email address.
      placeholder: tonyStark01, loki01
    validations:
      required: true
  - type: input
    id: External-Link
    attributes:
      label: External link
      description: Provide external url to your product/developer portal if you have chosen 'Link out' as the 'Type of Tenant'
      placeholder: https://www.fiserv.com
  - type: dropdown
    id: Internal-Tenant
    attributes:
        label: Internal tenant
        description: Is this product only for Fiserv's internal use? If not sure, please select 'No'
        options:
         - "Yes"
         - "No"
    validations:
      required: true
  - type: dropdown
    id: Carat
    attributes:
        label: Product of Carat
        description: Is this product for Fiserv's Carat Solutions? If not sure, please select 'No'
        options:
         - "Yes"
         - "No"
    validations:
      required: true
  - type: dropdown
    id: Product-Areas-Merchants
    attributes:
        label: Merchants solution area
        description: Does you product fall under Merchants category?
        options:
         - "Yes"
         - "No"
    validations:
      required: true
  - type: checkboxes
    id: customer-segments-for-merchants
    validations:
      required: true
    attributes:
      label: Customer Segments for Merchants
      description: Specify the type of integration required.
      options:
      - label: SMB
      - label: Enterprise
  - type: dropdown
    id: Product-Areas-Financial-Institutions
    attributes:
        label: Financial Institutions solution area
        description: Does you product fall under Financial Institutions category?
        options:
         - "Yes"
         - "No"
    validations:
      required: true
  - type: checkboxes
    id: customer-segments-for-financial-institutions
    validations:
      required: true
    attributes:
      label: Customer Segments for Merchants
      description: Specify the type of integration required.
      options:
       - label: Bank
       - label: Credit Union
       - label: Large Financial Institution
  - type: dropdown
    id: Product-Areas-Fintech
    attributes:
        label: Fintech solution area
        description: Does you product fall under Fintech category?
        options:
         - "Yes"
         - "No"
    validations:
      required: true
      
      
      
      
      
      
      
    
  - type: dropdown
    id: location
    attributes:
      label: Project Location
      description: Where is the project located?
      options:
        - Local
        - Remote
        - Somewhere else (please specify in the description!)
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: What happened?
    
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Which steps do we need to take to reproduce this error?
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, provide relevant log output. No need for backticks here.
      render: shell
