name: Guthub User activity

on:
  workflow_call:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 15 2 * *' 

jobs:
  guthub_User_activity:
    runs-on: ubuntu-latest
    steps:
      - name: User_activity
        id: analyze_user_activity
        uses: peter-murray/inactive-users-action@v1
        with:
         #repository: ${{ github.repository }}
         #path: ${{ github.workspace }}
         token: ${{secrets.API_KEY_GITHUB }}
         organization: Fiserv
         activity_days: 30

      - name: Save User Activity Report
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: |
            ${{ steps.analyze_user_activity.outputs.report_csv}}
