name: Guthub User activity

on:
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  guthub_User_activity:
    runs-on: ubuntu-latest
    steps:
      - name: User_activity 
        uses: peter-murray/inactive-users-action@v1
        with:
         repository: ${{ github.repository }}
         path: ${{ github.workspace }}
         #token: ${{secrets.API_TOKEN_GITHUB }}
         organization: Fiserv
         activity_days: 90

# - name: Save User Activity Report
#   uses: actions/upload-artifact@v2
#   with:
#     name: reports
#     path: |
#       ${{ steps.analyze_user_activity.outputs./.github/report_cvs.txt}}
