name: Calling Remote onBoarding Service

on:
  workflow_call:
  issues:
    types:
      - opened
      - labeled
    label:
      - 'Onboard New Tenant'

jobs:
  Tenant-Service:
    runs-on: ubuntu-latest
    steps:
    - name: View issue information
    run: |
    echo "Issue title: ${{ github.event.issue.title }}"
    echo "Issue body: ${{ github.event.issue.body }}"
