name: Calling Remote onBoarding Service

on:
  issues:
#     types:
#       - opened
#       - labeled
#     label:
#       - 'Onboard New Tenant'

jobs:
  Tenant-Service:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 Issue title ${{ github.event.issue.title}} and ${{ github.event.issue.body }}"
    
