name: OnBoarding_Service

on:
  workflow_call:  
  issues:
    types:
      - labeled

jobs:
  Tenant-Onboarding-Process:
    if: github.event.label.name == 'Onboard New Tenant'
    runs-on: ubuntu-latest
    steps:
      - name: View issue information
        run: |
          echo "Issue title: ${{ github.event.issue }}"
          echo "Issue No: ${{ github.event.issue.number }}"
          echo "Issue body: ${{ github.event.issue.body }}"
    
