name: OnBoarding_Service

on:
  workflow_call:  
  issues:
    types:
      - labeled

jobs:
  Tenant-Onboarding-Process:
    if: github.event.label.name == 'Onboard New Tenant'
    runs-on: ubuntu-latest
    steps:
      - name: View issue information
        run: |
          echo "🎉 The job automatically triggered by a ${{ github.event_name }} event."
          echo "Issue title: ${{ github.event.issue }}"
          echo "Issue No: ${{ github.event.issue.number }}"
          echo "Issue body: ${{ github.event.issue.body }}"
      - name: Creating new Temp sub dir 'service'
        run:  |
         mkdir -m 777 service
         cd service
         pwd
         ls -la
      - name: Checkout /Fiserv/tenant-onboarding Repo at ${{ github.workspace }}/service
        uses: actions/checkout@v3
        with:
         repository: Fiserv/tenant-onboarding
         ref: develop
         path: ${{ github.workspace }}/service
      - name: List files in the repository
        run: |
         cd ${{ github.workspace }}
         pwd
         ls -la
         cd ${{ github.workspace }}/service
         pwd
         ls -la
      - run: echo "💡 The Fiserv/tenant-onboarding repository has been cloned on root"
      - run: echo "🖥️ The workflow is now ready to run Onboarding service on the runner." 
      - name: List files in the repository
        run: |
         pwd
         ls -la             
      - name: Running Tenant Generator.....
        run: |
          pwd
          cd ${{github.workspace}}/service/scripts
          ls -la
          npmv=$(npm --version)
          echo "NPM version installed : " $npmv
          nodev=$(node --version)
          echo "Node version installed : " $nodev
          npm install
          echo " Repo: ${{ github.repository }}"
          echo " Space: ${{ github.workspace }}"
          result=$(npm run start ${{ github.event.issue.number }})
          echo "**********TEST RESULTS*********************"
          echo "$result"
          if [[ $result == *'FAILED'* ]] ;then
          echo "Onboarding config writer failed and exiting the Job..."
          exit 1
          elif [[ $result == *'PASSED'* ]] ;then
          echo "Onboarding config writer Ran Successfully....🍏"
          fi          
        #run: ./startup.sh -f '-rthe'
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Push tenant.json file to New Teanant Repository
        uses: nkoppel/push-files-to-another-repository@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: '${{github.workspace}}/service/tenant.json'
          destination-username: 'Fiserv'
          destination-repository: 'Fiserv/RustTenant'
          destination-directory: 'RustTenant/config'
          destination-branch: 'develop'
          commit-email: 'abhishek.singh3@fiserv.com'
          commit-message: 'Pushing Tenant.json file to new Teannt Repo'
