name: Calling Remote onBoarding Service

on:
  issues:
    types:
      - opened
      - labeled
    label:
      - 'Onboard New Tenant'

jobs:
  Tenant-Service:
    runs-on: ubuntu-latest
    steps:
    - name: View issue information
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event.issue.title }}."